# Generated by Django 2.2.6 on 2019-10-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KafyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='team',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='question',
            name='user_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='KafyApp.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit',
            name='user_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='KafyApp.UserInfo'),
            preserve_default=False,
        ),
    ]
